# Generated by Django 3.0.6 on 2021-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210323_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Category'),
        ),
    ]
