# Generated by Django 3.0.6 on 2021-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210326_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(blank=True, to='myapp.Category'),
        ),
    ]
